FROM alpine:latest AS downloader
RUN apk add --no-cache curl tar bzip2 binutils

FROM downloader AS stage-amd64
RUN mkdir -p /opt/toolchains/amd64-musl-13.2 && \
    curl -SL https://toolchains.bootlin.com/downloads/releases/toolchains/x86-64/tarballs/x86-64--musl--bleeding-edge-2023.11-1.tar.bz2 | tar -jxf - -C /opt/toolchains/amd64-musl-13.2 --strip-components=1 && \
    rm -rf /opt/toolchains/amd64-musl-13.2/{share,doc,man,info}

FROM downloader AS stage-arm64
RUN mkdir -p /opt/toolchains/arm64-musl-13.2 && \
    curl -SL https://toolchains.bootlin.com/downloads/releases/toolchains/aarch64/tarballs/aarch64--musl--bleeding-edge-2023.11-1.tar.bz2 | tar -jxf - -C /opt/toolchains/arm64-musl-13.2 --strip-components=1 && \
    rm -rf /opt/toolchains/arm64-musl-13.2/{share,doc,man,info}

FROM downloader AS stage-arm
RUN mkdir -p /opt/toolchains/arm-musl-13.2 && \
    curl -SL https://toolchains.bootlin.com/downloads/releases/toolchains/armv7-eabihf/tarballs/armv7-eabihf--musl--bleeding-edge-2023.11-1.tar.bz2 | tar -jxf - -C /opt/toolchains/arm-musl-13.2 --strip-components=1 && \
    rm -rf /opt/toolchains/arm-musl-13.2/{share,doc,man,info}

FROM scratch
COPY --from=stage-amd64 /opt/ /
COPY --from=stage-arm64 /opt/ /
COPY --from=stage-arm /opt/ /