FROM alpine:latest AS downloader
RUN apk add --no-cache curl tar bzip2 xz binutils

FROM downloader AS stage-unpack

ARG DOWNLOAD_URL
ARG TARGET_DIR
WORKDIR /opt/toolchains

RUN mkdir -p ${TARGET_DIR} && \
    if [[ "${DOWNLOAD_URL}" == *.txz || "${DOWNLOAD_URL}" == *.tar.xz ]]; then OPT="-Jxf"; else OPT="-jxf"; fi && \
    curl -SL ${DOWNLOAD_URL} | tar ${OPT} - -C ${TARGET_DIR} --strip-components=1 && \
    rm -rf ${TARGET_DIR}/{share,doc,man,info} && \
    find ${TARGET_DIR}/bin ${TARGET_DIR}/libexec -type f -executable -exec strip --strip-unneeded {} + 2>/dev/null || true

FROM scratch
COPY --from=stage-unpack /opt/ /